spring:
  application:
    name: app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:hexlet-task-manager-super-secret-key-change-me-1234567890}
  expiration-ms: 86400000
